blas/blas.go, blas/generate_blas.go
@btracey @vladimir-ch Please take a look.
Fixes #3.
=> blas: don't panic for zero length slices

blas/netlib/generate_blas.go
=> travis: fix go generate check

blas/netlib/blas.go, blas/netlib/generate_blas.go
=> blas/netlib: fix dgbmv bounds checks

.travis.yml, blas/netlib/dtrmvbench_test.go, lapack/netlib/bench_test.go
=> all: remove go1.7 build constraints

blas/netlib/blas.go
=> blas/netlib: update generated docs

.travis.yml
=> travis: update testing matrix

.travis/linux/OpenBLAS/install.sh, README.md
=> doc,travis: clean-up

blas/netlib/blas.go, blas/netlib/level1cmplx128_test.go, blas/netlib/level2cmplx128_test.go
=> blas/netlib: enable test for complex128 BLAS level 1 and 2

.github/ISSUE_TEMPLATE
=> github: ask for netlib version too

.travis.yml
Failure will be due to Drotmg issue.
=> travis: add go-1.10.x

.github/ISSUE_TEMPLATE
=> github: fix typo in ISSUE_TEMPLATE

blas/netlib/blas.go, blas/netlib/level2cmplx128_test.go
=> blas/netlib: add docs and test for Ztpsv

blas/netlib/blas.go, blas/netlib/level2cmplx128_test.go
=> blas/netlib: run 'go generate' and add tests

lapack/netlib/lapack.go
=> lapack/netlib: let lapacke compute optimal work length for Dgeqrf

blas/netlib/blas.go, blas/netlib/level2cmplx128_test.go
=> blas/netlib: enable test for Ztbmv and Ztbsv

lapack/netlib/lapack.go, lapack/netlib/lapack_test.go
=> lapack/netlib: add Dpotrs

.travis.yml
=> travis: update matrix for supported versions

blas/netlib/blas.go, blas/netlib/generate_blas.go, lapack/lapacke/generate_lapacke.go, lapack/lapacke/lapacke.go, lapack/netlib/lapack.go
=> blas/netlib: convert blas char constants to CBLAS integers

lapack/netlib/lapack.go
=> netlib/lapack: rename SVDInPlace to SVDStore, NormFrob to Frobenius

.travis/test-coverage.sh, README.md
=> travis: send test coverage to codecov.io

.travis.yml, .travis/linux/OpenBLAS/install.sh, .travis/linux/OpenBLAS/test.sh
=> travis: run install and tests in new shells

lapack/netlib/generate_errors.go
=> lapack/netlib: return error on go list failure

go.mod, go.sum
=> modules: bump gonum version to v0.7.0

go.mod, go.sum, lapack/netlib/lapack.go, lapack/netlib/lapack_test.go
Merging of this will have to wait until the dependence of the test on Dlansb is removed in the main repo.
=> lapack/netlib: add Dpbcon

.codecov.yml, .github/workflows/ci.yml, .github/workflows/codecov.yml, .github/workflows/install-openblas.sh, .github/workflows/test-coverage.sh, .github/workflows/test.sh
=> ci: test with github actions

.github/workflows/ci.yml, .github/workflows/codecov.yml, .travis.yml
=> ci: bump Go version to 1.16

.github/workflows/check-copyright.sh, .github/workflows/check-formatting.sh, .github/workflows/check-generate.sh, .github/workflows/check-imports.sh, .github/workflows/ci.yml, .github/workflows/codecov.yml, .github/workflows/install-openblas.sh, .github/workflows/test.sh, go.mod
=> ci: update
